// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjrfdglwtpdtfkiluwah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqcmZkZ2x3dHBkdGZraWx1d2FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5Nzc3NDgsImV4cCI6MjA3NDU1Mzc0OH0.Y_MTY7yyZsgv2AWhknCab-m7-AjiYFyXJKJM2L76gP4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});